apiVersion: v1
kind: Secret
metadata:
  name: mongo
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  BUCKET_URI: {{ .Values.backup.bucket_uri | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  AWS_DEFAULT_REGION: {{ .Values.backup.aws_default_region | b64enc | quote }}
