## Full restore
auth:
  rootUser: root
  rootPassword: "${mongodb_root_user_password}"

restore:
  bucket_uri: ${bucket_uri}
  file_name: ${file_name}
  aws_default_region: ${s3_bucket_region}

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}
