## Enable Full backup
auth:
  rootUser: root
  rootPassword: "${mongodb_root_user_password}"

backup:
  bucket_uri: ${bucket_uri}
  aws_default_region: ${s3_bucket_region}
  cron_for_full_backup: "${cron_for_full_backup}"

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}
